<!DOCTYPE html>
<html lang="en"><head>
<script src="drift_diffusion_modeling_files/libs/clipboard/clipboard.min.js"></script>
<script src="drift_diffusion_modeling_files/libs/quarto-html/tabby.min.js"></script>
<script src="drift_diffusion_modeling_files/libs/quarto-html/popper.min.js"></script>
<script src="drift_diffusion_modeling_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="drift_diffusion_modeling_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="drift_diffusion_modeling_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="drift_diffusion_modeling_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Dr.&nbsp;Bernhard Angele">
  <title>Drift Diffusion Modeling in R with brms &amp; cogmod</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="drift_diffusion_modeling_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="drift_diffusion_modeling_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="drift_diffusion_modeling_files/libs/revealjs/dist/theme/quarto-221e871ebcaed704597e7b338bddf024.css">
  <link href="drift_diffusion_modeling_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="drift_diffusion_modeling_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="drift_diffusion_modeling_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="drift_diffusion_modeling_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Drift Diffusion Modeling in R with brms &amp; cogmod</h1>
  <p class="subtitle">It can be done!</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Bernhard Angele 
</div>
</div>
</div>

  <p class="date">Tuesday, September 8, 2026</p>
</section>
<section id="context-within-the-ddm-workshop" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Context within the DDM Workshop</h2>
<div style="background: linear-gradient(135deg, #1F497D, #C2002F); color: white; padding: 22px; border-radius: 10px; text-align: center; margin-bottom: 25px; font-weight: bold; font-size: 1.15em; box-shadow: 0 4px 10px rgba(0,0,0,0.15);">
<p>Module: Technical Issues in brms &amp; How cogmod Works</p>
</div>
<h3 id="from-mathematical-theory-to-computational-reality">From Mathematical Theory to Computational Reality</h3>
<ul>
<li class="fragment">Earlier sessions cover the <strong>conceptual and mathematical foundations</strong> of evidence accumulation (Wiener diffusion equations, boundary hitting times, speed-accuracy tradeoffs).</li>
<li class="fragment"><strong>Our Focus in this Module:</strong>
<ul>
<li class="fragment">The <strong>computational hurdles</strong> of fitting hierarchical DDMs with Hamiltonian Monte Carlo (HMC) in Stan/<code>brms</code>.</li>
<li class="fragment">How <strong><code>cogmod</code></strong> resolves the infamous numerical pathologies of native Stan.</li>
<li class="fragment">Specific design considerations for our <strong>stimulus-coded model</strong> (<code>fit_ddm_stimulus_coding.R</code>).</li>
<li class="fragment">Orthogonal contrast engineering, multithreading, and sampler diagnostics.</li>
</ul></li>
</ul>
</section>
<section id="workshop-module-agenda" class="slide level2">
<h2>Workshop Module Agenda</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="technical-hurdles-in-brms">1. Technical Hurdles in brms</h3>
<ul>
<li class="fragment">Native Stan limitations (<code>wiener_lpdf</code>)</li>
<li class="fragment">The NaN partial gradient disaster</li>
<li class="fragment">The hard minimum-RT cliff &amp; crashes</li>
<li class="fragment">Crossed random effects complexity</li>
</ul>
<h3 id="how-cogmod-works-under-the-hood">2. How cogmod Works Under the Hood</h3>
<ul>
<li class="fragment">Custom family architecture (<code>cogmod_ddm</code>)</li>
<li class="fragment">Link functions: Why <code>softplus</code> for boundary?</li>
<li class="fragment">The 0.2s half-normal outlier mixture</li>
<li class="fragment">The triad: <code>priors</code>, <code>inits</code>, and <code>stanvars</code></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="considerations-for-our-model">3. Considerations for Our Model</h3>
<ul>
<li class="fragment">Response coding vs.&nbsp;Error coding</li>
<li class="fragment">Data censoring (<code>speed_acc$censor</code>)</li>
<li class="fragment">Collapsing stimulus levels (low + very low)</li>
<li class="fragment">Empirical 50/50 response balance</li>
</ul>
<h3 id="contrasts-interpretation">4. Contrasts &amp; Interpretation</h3>
<ul>
<li class="fragment">Orthogonal Helmert contrasts</li>
<li class="fragment">Sum-to-zero instruction contrasts</li>
<li class="fragment">Deconstructing the drift rate intercept</li>
</ul>
<h3 id="high-performance-sampling">5. High-Performance Sampling</h3>
<ul>
<li class="fragment">Within-chain multi-threading (<code>threading(2)</code>)</li>
<li class="fragment">Diagnosing &amp; preventing divergences</li>
</ul>
</div></div>
</section>
<section id="part-1-technical-hurdles-of-ddm-in-brms" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Part 1: Technical Hurdles of DDM in brms</h2>
</section>
<section id="the-high-dimensionality-of-cognitive-models" class="slide level2">
<h2>The High Dimensionality of Cognitive Models</h2>
<ul>
<li class="fragment">In psychological and psycholinguistic experiments (e.g., lexical decision), we have <strong>crossed random effects</strong>: <span class="math display">\[\text{Drift Rate } \mu_{ij} = \beta_0 + \beta_1 X_{ij} + u_i + w_j, \quad u_i \sim \text{Normal}(0, \sigma_{\text{Participant}}^2), \quad w_j \sim \text{Normal}(0, \sigma_{\text{Item}}^2)\]</span></li>
<li class="fragment">Unlike nested clinical trials, every participant responds to hundreds of unique items.</li>
<li class="fragment">In Wagenmakers et al.&nbsp;(2008), this means estimating:
<ul>
<li class="fragment"><strong>4 core cognitive parameters</strong> (<span class="math inline">\(\mu, a, t_0, z\)</span>) across condition cells.</li>
<li class="fragment"><strong>Crossed random intercepts</strong> across <span class="math inline">\(3\)</span> participants and <span class="math inline">\(&gt;3,000\)</span> items.</li>
<li class="fragment">Over <strong><span class="math inline">\(3,000\)</span> latent parameters</strong> estimated simultaneously!</li>
</ul></li>
<li class="fragment">Fitting this via Hamiltonian Monte Carlo requires an exceptionally stable posterior geometry.</li>
</ul>
</section>
<section id="native-stan-brmswiener-limitations" class="slide level2">
<h2>Native Stan &amp; <code>brms::wiener()</code> Limitations</h2>
<p>Standard <code>brms</code> includes the <code>wiener()</code> family <span class="citation" data-cites="burkner2017brms singmann2017wiener">(<a href="#/references" role="doc-biblioref" onclick="">Bürkner, 2017</a>; <a href="#/references" role="doc-biblioref" onclick="">Singmann, 2017</a>)</span>, but fitting hierarchical models often hits severe technical roadblocks:</p>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="the-nan-gradient-disaster">1. The NaN Gradient Disaster</h3>
<ul>
<li class="fragment">Stan’s <code>wiener_lpdf()</code> evaluates alternating infinite series (Navarro &amp; Fuss, 2009).</li>
<li class="fragment">When density underflows to 0, it returns <code>-inf</code> with <strong>NaN partial derivatives</strong>!</li>
<li class="fragment">In reverse-mode automatic differentiation: <span class="math display">\[0 \times \text{NaN} = \text{NaN}\]</span></li>
<li class="fragment">A single trial with a NaN partial turns the <strong>entire model gradient to NaN</strong>!</li>
<li class="fragment">Leads to “Non-finite gradient” aborts and false divergent transitions.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="the-hard-min-rt-cliff">2. The Hard Min-RT Cliff</h3>
<ul>
<li class="fragment">The Wiener process is undefined for <span class="math inline">\(RT \le t_0\)</span>.</li>
<li class="fragment">If a single trial has <span class="math inline">\(RT \le t_0\)</span>, density drops to 0 instantly as an <strong>infinite vertical cliff</strong>.</li>
<li class="fragment">Stan cannot calculate gradients across discontinuities.</li>
<li class="fragment">Warmup chains get trapped or fail during initialization: <em>“Rejecting initial value: Log probability evaluates to log(0)”</em></li>
<li class="fragment">Forces brittle manual bounds (<span class="math inline">\(t_0 &lt; \min(RT)\)</span>).</li>
</ul>
</div></div>
</section>
<section id="units-matter-seconds-vs.-milliseconds" class="slide level2">
<h2>Units Matter: Seconds vs.&nbsp;Milliseconds!</h2>
<ul>
<li class="fragment">In standard linear regression, whether RT is in milliseconds (<span class="math inline">\(500\)</span> ms) or seconds (<span class="math inline">\(0.50\)</span> s) only scales the slope by <span class="math inline">\(1000\)</span>.</li>
<li class="fragment"><strong>In Drift Diffusion Modeling, units are fundamental:</strong>
<ul>
<li class="fragment">Diffusion variance <span class="math inline">\(s^2\)</span> is fixed to <span class="math inline">\(1\)</span> (or <span class="math inline">\(0.1\)</span>) as an arbitrary scaling constant.</li>
<li class="fragment">All four parameters (<span class="math inline">\(\mu, a, t_0, z\)</span>) scale nonlinearly with time units: <span class="math display">\[a \propto \sqrt{\text{time}}, \quad \mu \propto \frac{1}{\sqrt{\text{time}}}, \quad t_0 \propto \text{time}\]</span></li>
<li class="fragment">Stan’s numerical precision and internal approximations are calibrated for <strong>SECONDS</strong>.</li>
<li class="fragment">If you pass reaction times in milliseconds (<span class="math inline">\(500\)</span> instead of <span class="math inline">\(0.5\)</span>), Stan’s exponential and Bessel approximations overflow/underflow immediately!</li>
</ul></li>
<li class="fragment"><strong>Golden Rule:</strong> Always verify that <span class="math inline">\(RT\)</span> is in seconds (<span class="math inline">\(0.18 \le RT \le 3.0\)</span>) before fitting!</li>
</ul>
</section>
<section id="part-2-how-cogmod-works-under-the-hood" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Part 2: How cogmod Works Under the Hood</h2>
</section>
<section id="what-is-cogmod-makowski2025cogmod" class="slide level2">
<h2>What is <code>cogmod</code>? <span class="citation" data-cites="makowski2025cogmod">(<a href="#/references" role="doc-biblioref" onclick="">Makowski, 2025</a>)</span></h2>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li class="fragment">Developed by Dominique Makowski (2025).</li>
<li class="fragment">Designed specifically to bridge cognitive science models with modern Bayesian computation in <code>brms</code> and Stan.</li>
<li class="fragment">Provides <code>cogmod_ddm()</code>: a <strong>custom <code>brms</code> distributional family</strong> (<code>custom_family</code>).</li>
<li class="fragment">Parameterizes the decision process:
<ul>
<li class="fragment"><code>mu</code>: Drift rate (accumulation slope)</li>
<li class="fragment"><code>boundary</code>: Boundary separation (<span class="math inline">\(a &gt; 0\)</span>)</li>
<li class="fragment"><code>ndt</code>: Non-decision time (<span class="math inline">\(t_0 &gt; 0\)</span>)</li>
<li class="fragment"><code>bias</code>: Relative starting point (<span class="math inline">\(z/a \in (0, 1)\)</span>)</li>
<li class="fragment"><code>sigmadrift</code>, <code>sigmabias</code>, <code>sigmandt</code>: Trial-to-trial variabilities (7-parameter Ratcliff DDM)</li>
<li class="fragment"><code>poutlier</code>: Proportion of lapse trials</li>
</ul></li>
</ul>
</div><div class="column" style="width:45%;">
<div style="background: #F4F6F9; border-left: 5px solid #1F497D; padding: 15px; border-radius: 6px; font-size: 0.9em;">
<p><strong>Core Advantages of cogmod:</strong><br><br> ✅ <strong>Safe Likelihood:</strong> Dual Navarro &amp; Fuss approximations prevent NaN gradients.<br><br> ✅ <strong>Outlier Mixture:</strong> Eliminates the hard minimum-RT cliff.<br><br> ✅ <strong>Stable Link Functions:</strong> Uses softplus for boundary separation.<br><br> ✅ <strong>Automated Workflows:</strong> Built-in priors, smart initializations, and Stan code injection.</p>
</div>
</div></div>
</section>
<section id="parameter-link-functions-in-cogmod" class="slide level2">
<h2>Parameter Link Functions in <code>cogmod</code></h2>
<p>In distributional regression, parameters are modeled on unbounded latent scales via link functions:</p>
<table class="caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Link Function</th>
<th style="text-align: center;">Mathematical Form</th>
<th style="text-align: left;">Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Drift Rate (<span class="math inline">\(\mu\)</span>)</strong></td>
<td style="text-align: center;"><code>identity</code></td>
<td style="text-align: center;"><span class="math inline">\(\mu = \eta\)</span></td>
<td style="text-align: left;">Can take any real value (<span class="math inline">\(-\infty, +\infty\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Boundary (<span class="math inline">\(a\)</span>)</strong></td>
<td style="text-align: center;"><strong><code>softplus</code></strong></td>
<td style="text-align: center;"><span class="math inline">\(a = \log(1 + e^{\eta})\)</span></td>
<td style="text-align: left;"><strong>Smooth positive gradient!</strong> (Avoids log explosions)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Non-decision (<span class="math inline">\(t_0\)</span>)</strong></td>
<td style="text-align: center;"><code>log</code></td>
<td style="text-align: center;"><span class="math inline">\(t_0 = e^{\eta}\)</span></td>
<td style="text-align: left;">Strictly positive latency (<span class="math inline">\(t_0 &gt; 0\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Bias (<span class="math inline">\(z/a\)</span>)</strong></td>
<td style="text-align: center;"><code>logit</code></td>
<td style="text-align: center;"><span class="math inline">\(z = \frac{1}{1 + e^{-\eta}}\)</span></td>
<td style="text-align: left;">Strictly bounded within <span class="math inline">\((0, 1)\)</span> (<span class="math inline">\(0.5 = \text{unbiased}\)</span>)</td>
</tr>
</tbody>
</table>
<div style="background: #E8F4F8; border-left: 5px solid #1F497D; padding: 10px; margin-top: 15px; font-size: 0.9em;">
<p>💡 <strong>Why <code>softplus</code> for Boundary instead of <code>log</code>?</strong><br> A <code>log</code> link models <span class="math inline">\(a = \exp(\eta)\)</span>. If predictors yield <span class="math inline">\(\eta &gt; 3\)</span>, boundary separation explodes exponentially, collapsing the likelihood. The <code>softplus</code> function behaves linearly for positive values (<span class="math inline">\(\approx \eta\)</span>) and smoothly approaches zero for negative values, providing robust HMC gradients!</p>
</div>
</section>
<section id="the-outlier-mixture-mechanism" class="slide level2">
<h2>The Outlier Mixture Mechanism</h2>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li class="fragment"><strong>How cogmod eliminates the min-RT cliff:</strong></li>
<li class="fragment">Blends the Wiener density with a <strong>half-normal outlier lapse process</strong> (scale = <span class="math inline">\(0.2\)</span> s) with equal choice probability: <span class="math display">\[p(\text{choice}, RT) = (1 - p_{\text{out}}) f_{\text{Wiener}} + p_{\text{out}} f_{\text{Lapse}}\]</span></li>
<li class="fragment">If <span class="math inline">\(RT \le t_0\)</span>:
<ul>
<li class="fragment">Standard Wiener crashes to <span class="math inline">\(-\infty\)</span> with NaN partials.</li>
<li class="fragment"><code>cogmod</code> smoothly assigns: <span class="math display">\[\log(p_{\text{outlier}}) + lp_{\text{outlier}}\]</span></li>
</ul></li>
<li class="fragment">The parameter <span class="math inline">\(t_0\)</span> can now be estimated via smooth gradients without hitting an impenetrable cliff!</li>
</ul>
</div><div class="column" style="width:55%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/cogmod_outlier_mixture.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="the-triad-of-automation-helpers" class="slide level2">
<h2>The Triad of Automation Helpers</h2>
<p><code>cogmod</code> provides three dedicated functions that work in concert with <code>brms</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="co"># 1. Automatic data-driven priors matched to parameter link scales</span></span>
<span id="cb1-2"><a href=""></a>prior_ddm <span class="ot">&lt;-</span> <span class="fu">cogmod_priors</span>(f_ddm, df)</span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a><span class="co"># 2. Smart initialization function avoiding boundary rejection</span></span>
<span id="cb1-5"><a href=""></a>init_ddm  <span class="ot">&lt;-</span> <span class="fu">cogmod_inits</span>(f_ddm, df)</span>
<span id="cb1-6"><a href=""></a></span>
<span id="cb1-7"><a href=""></a><span class="co"># 3. Stan C++ code injection for the custom likelihood functions</span></span>
<span id="cb1-8"><a href=""></a>sv_ddm    <span class="ot">&lt;-</span> <span class="fu">cogmod_stanvars</span>(f_ddm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="columns">
<div class="column" style="width:33%;">
<h4 id="cogmod_priors">cogmod_priors()</h4>
<p>Generates weakly informative priors scaled specifically for seconds and link functions (e.g.&nbsp;Normal priors on logit bias, softplus boundary).</p>
</div><div class="column" style="width:33%;">
<h4 id="cogmod_inits">cogmod_inits()</h4>
<p>Calculates empirical RT minima and provides jittered starting values ensuring <span class="math inline">\(t_0 &lt; \min(RT)\)</span> for every chain. Eliminates initialization crashes!</p>
</div><div class="column" style="width:33%;">
<h4 id="cogmod_stanvars">cogmod_stanvars()</h4>
<p>Injects custom C++ Stan code (<code>cogmod_ddm_lpdf</code>, dual Navarro &amp; Fuss series) directly into Stan’s <code>functions {}</code> block.</p>
</div></div>
</section>
<section id="part-3-considerations-for-this-particular-model" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Part 3: Considerations for THIS Particular Model</h2>
<h3 id="workshop_sepexfit_ddm_stimulus_coding.r"><code>workshop_sepex/fit_ddm_stimulus_coding.R</code></h3>
</section>
<section id="response-coding-vs.-error-coding" class="slide level2">
<h2>Response Coding vs.&nbsp;Error Coding</h2>
<p>A foundational decision in DDM specification is how boundaries are mapped to behavior:</p>
<div class="columns">
<div class="column" style="width:50%;">
<h4 id="accuracy-error-coding">Accuracy / Error Coding</h4>
<ul>
<li class="fragment"><strong>Lower (0):</strong> Correct response</li>
<li class="fragment"><strong>Upper (1):</strong> Error response</li>
<li class="fragment"><strong>Fatal Flaw in Lexical Decision:</strong>
<ul>
<li class="fragment">Accuracy is typically ~95%.</li>
<li class="fragment"><strong>95% of data hits boundary 0</strong>; only 5% hits boundary 1.</li>
<li class="fragment">Severe data sparsity prevents reliable estimation of boundary <span class="math inline">\(a\)</span> and non-decision time <span class="math inline">\(t_0\)</span>.</li>
<li class="fragment">Erases physical motor key distinctions.</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<h4 id="response-stimulus-coding">Response / Stimulus Coding</h4>
<ul>
<li class="fragment"><strong>Lower (0):</strong> “Nonword” key press</li>
<li class="fragment"><strong>Upper (1):</strong> “Word” key press</li>
<li class="fragment"><strong>Methodological Strengths:</strong>
<ul>
<li class="fragment"><strong>Balanced boundaries:</strong> ~50/50 distribution of observations (<span class="math inline">\(47\%\)</span> word, <span class="math inline">\(53\%\)</span> nonword).</li>
<li class="fragment">Both boundaries have thousands of empirical RTs.</li>
<li class="fragment"><strong>Direct motor mapping:</strong> Starting point bias (<span class="math inline">\(z &gt; 0.5\)</span>) measures true preference toward “Word”.</li>
<li class="fragment"><strong>Directional drift:</strong> <span class="math inline">\(v &gt; 0\)</span> for words, <span class="math inline">\(v &lt; 0\)</span> for nonwords!</li>
</ul></li>
</ul>
</div></div>
</section>
<section id="data-censoring-via-speed_acccensor" class="slide level2">
<h2>Data Censoring via <code>speed_acc$censor</code></h2>
<ul>
<li class="fragment">We fit Experiment 1 of Wagenmakers et al.&nbsp;(2008), provided in <code>rtdists::speed_acc</code> <span class="citation" data-cites="heathcote2012linear singmann2017wiener">(<a href="#/references" role="doc-biblioref" onclick="">Heathcote &amp; Love, 2012</a>; <a href="#/references" role="doc-biblioref" onclick="">Singmann, 2017</a>)</span>.</li>
<li class="fragment"><strong>Why we filter <code>!speed_acc$censor</code>:</strong>
<ul>
<li class="fragment">Wagenmakers et al.&nbsp;and Heathcote &amp; Love (2012) flagged <span class="math inline">\(171\)</span> trials (<span class="math inline">\(0.5\%\)</span>) for exclusion:
<ul>
<li class="fragment"><strong>Accidental button presses:</strong> Keys pressed outside the designated response set.</li>
<li class="fragment"><strong>Fast anticipations (<span class="math inline">\(RT &lt; 180\)</span> ms):</strong> Responses faster than physiological visual-motor transmission time.</li>
<li class="fragment"><strong>Attentional lapses (<span class="math inline">\(RT &gt; 3.0\)</span> s):</strong> Trials with mind-wandering or external disruption.</li>
</ul></li>
<li class="fragment"><strong>Technical impact on brms:</strong>
<ul>
<li class="fragment">Extreme anticipations artificially compress the estimate of <span class="math inline">\(t_0\)</span>.</li>
<li class="fragment">Long lapses artificially inflate boundary separation <span class="math inline">\(a\)</span>.</li>
<li class="fragment">Filtering <code>!censor</code> yields <span class="math inline">\(4,632\)</span> clean observations for participants 1–3.</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="collapsing-stimulus-types" class="slide level2">
<h2>Collapsing Stimulus Types</h2>
<p>In the original Wagenmakers et al.&nbsp;(2008) dataset, stimuli are divided into 4 categories: - <code>nonword</code>, <code>very_low</code>, <code>low</code>, and <code>high</code> frequency.</p>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="the-collapsing-strategy">The Collapsing Strategy</h3>
<ul>
<li class="fragment">Words with <code>very_low</code> and <code>low</code> frequency exhibit near-identical lexical access latencies.</li>
<li class="fragment">Estimating separate parameters for both fragments statistical power without theoretical benefit.</li>
<li class="fragment">We collapse them into a single level: <strong><code>low</code></strong>.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="resulting-parsimonious-factor">Resulting Parsimonious Factor</h3>
<ol type="1">
<li class="fragment"><strong><code>nonword</code></strong> (<span class="math inline">\(N = 2,311\)</span> trials)
<ul>
<li class="fragment">Pseudoword items requiring negative drift.</li>
</ul></li>
<li class="fragment"><strong><code>low</code></strong> (<span class="math inline">\(N = 1,547\)</span> trials)
<ul>
<li class="fragment">Combined low &amp; very low frequency words.</li>
</ul></li>
<li class="fragment"><strong><code>high</code></strong> (<span class="math inline">\(N = 774\)</span> trials)
<ul>
<li class="fragment">High frequency, easily recognized words.</li>
</ul></li>
</ol>
</div></div>
</section>
<section id="empirical-distributions-clean-5050-split" class="slide level2">
<h2>Empirical Distributions: Clean 50/50 Split</h2>

<img data-src="drift_diffusion_modeling_files/figure-revealjs/empirical-stim-plot-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="part-4-contrast-design-intercept-mechanics" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Part 4: Contrast Design &amp; Intercept Mechanics</h2>
</section>
<section id="the-trap-of-default-treatment-coding" class="slide level2">
<h2>The Trap of Default Treatment Coding</h2>
<ul>
<li class="fragment">By default, R and <code>brms</code> use <strong>dummy / treatment coding</strong> (<code>contr.treatment</code>).</li>
<li class="fragment">It designates one factor level as the baseline (e.g.&nbsp;High Frequency Words under Accuracy).</li>
<li class="fragment"><strong>Why this fails in multi-parameter DDM:</strong>
<ul>
<li class="fragment">The drift rate intercept <span class="math inline">\(\beta_0\)</span> becomes the drift rate <em>of high-frequency words in accuracy conditions</em>.</li>
<li class="fragment">Main effects represent differences from that specific condition, not average marginal effects.</li>
<li class="fragment">Testing whether drift rate differs between words and nonwords requires awkward linear combinations (<code>hypothesis()</code>).</li>
</ul></li>
<li class="fragment"><strong>Solution:</strong> Planned <strong>Orthogonal Helmert Contrasts</strong> and <strong>Sum Contrasts</strong> <span class="citation" data-cites="schad2020how">(<a href="#/references" role="doc-biblioref" onclick="">Schad et al., 2020</a>)</span>.</li>
</ul>
</section>
<section id="orthogonal-helmert-contrasts-for-stimulus_type" class="slide level2">
<h2>Orthogonal Helmert Contrasts for <code>stimulus_type</code></h2>
<p>We structure two planned, orthogonal hypotheses:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>helmert_mat <span class="ot">&lt;-</span> <span class="fu">contr.helmert</span>(<span class="dv">3</span>)[, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>)]</span>
<span id="cb2-2"><a href=""></a><span class="fu">colnames</span>(helmert_mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Nonword_vs_Word"</span>, </span>
<span id="cb2-3"><a href=""></a>                           <span class="st">"Low_vs_High"</span>)</span>
<span id="cb2-4"><a href=""></a><span class="fu">contrasts</span>(df<span class="sc">$</span>stimulus_type) <span class="ot">&lt;-</span> helmert_mat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stimulus Level</th>
<th style="text-align: center;"><code>Nonword_vs_Word</code></th>
<th style="text-align: center;"><code>Low_vs_High</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>High Word</strong></td>
<td style="text-align: center;"><span class="math inline">\(-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Low Word</strong></td>
<td style="text-align: center;"><span class="math inline">\(-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(+1\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Nonword</strong></td>
<td style="text-align: center;"><span class="math inline">\(+2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment"><span class="math inline">\(\sum C_1 = 0\)</span>, <span class="math inline">\(\sum C_2 = 0\)</span> (centered).</li>
<li class="fragment">Dot product: <span class="math inline">\((-1)(-1) + (-1)(1) + (2)(0) = 0\)</span> (<strong>orthogonal!</strong>).</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/stimulus_coding_contrasts.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="sum-contrasts-for-condition" class="slide level2">
<h2>Sum Contrasts for <code>Condition</code></h2>
<p>For speed vs.&nbsp;accuracy instructions, we apply <strong>Sum-to-Zero contrasts</strong> (<code>contr.sum</code>):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="fu">contrasts</span>(df<span class="sc">$</span>Condition) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)</span>
<span id="cb3-2"><a href=""></a><span class="fu">colnames</span>(<span class="fu">contrasts</span>(df<span class="sc">$</span>Condition)) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Acc_vs_Speed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Instruction Condition</th>
<th style="text-align: center;"><code>Acc_vs_Speed</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Accuracy</strong></td>
<td style="text-align: center;"><span class="math inline">\(+1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Speed</strong></td>
<td style="text-align: center;"><span class="math inline">\(-1\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li class="fragment"><strong>Properties:</strong>
<ul>
<li class="fragment">Column sums to zero: <span class="math inline">\((+1) + (-1) = 0\)</span>.</li>
<li class="fragment">Intercept reflects the <strong>unweighted grand mean</strong> across instructions.</li>
<li class="fragment">Predictor tests the average directional difference between Accuracy and Speed blocks.</li>
</ul></li>
</ul>
</section>
<section id="interpretability-meaning-of-the-drift-intercept" class="slide level2">
<h2>Interpretability: Meaning of the Drift Intercept</h2>
<p>Because all contrast columns sum to zero across factor levels, the intercept <span class="math inline">\(\beta_0\)</span> is evaluated where all predictors equal zero: <span class="math display">\[\beta_0 = \frac{1}{3}\mu_{\text{high}} + \frac{1}{3}\mu_{\text{low}} + \frac{1}{3}\mu_{\text{nonword}}\]</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<h4 id="directional-cancellation-imbalance">1. Directional Cancellation &amp; Imbalance</h4>
<ul>
<li class="fragment">Words pull positive (<span class="math inline">\(\mu_{\text{word}} &gt; 0\)</span>). Nonwords pull negative (<span class="math inline">\(\mu_{\text{nonword}} &lt; 0\)</span>). They pull in opposite directions and partially cancel out!</li>
<li class="fragment">There are 2 word categories and 1 nonword category: <span class="math display">\[\beta_0 = \frac{2}{3}\bar{\mu}_{\text{word}} + \frac{1}{3}\mu_{\text{nonword}}\]</span></li>
<li class="fragment">Even if words and nonwords are equally easy (<span class="math inline">\(|\bar{\mu}_{\text{w}}| = |\mu_{\text{nw}}|\)</span>), <span class="math inline">\(\beta_0\)</span> is naturally <strong>positive</strong>!</li>
</ul>
</div><div class="column" style="width:50%;">
<h4 id="where-does-discrimination-live">2. Where Does Discrimination Live?</h4>
<ul>
<li class="fragment">Under stimulus coding, <strong>overall discrimination ability lives in Helmert Contrast 1</strong> (<code>Nonword_vs_Word</code>): <span class="math display">\[\mu_{\text{nonword}} - \bar{\mu}_{\text{word}}\]</span></li>
<li class="fragment">Because words are positive and nonwords are negative, this contrast strongly captures the ability to separate words from nonwords!</li>
<li class="fragment">Lexical sensitivity lives in <strong>Helmert Contrast 2</strong> (<code>Low_vs_High</code>).</li>
</ul>
</div></div>
</section>
<section id="part-5-model-specification-multi-threading" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Part 5: Model Specification &amp; Multi-Threading</h2>
<h3 id="running-brms-with-cmdstanr">Running <code>brms</code> with <code>cmdstanr</code></h3>
</section>
<section id="the-stimulus-coded-ddm-formula" class="slide level2">
<h2>The Stimulus-Coded DDM Formula</h2>
<p>In <code>workshop_sepex/fit_ddm_stimulus_coding.R</code>, we specify the full distributional formula:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>f_ddm <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb4-2"><a href=""></a>  <span class="co"># 1. Drift Rate (mu): stimulus_type * Condition + crossed random intercepts</span></span>
<span id="cb4-3"><a href=""></a>  rt <span class="sc">|</span> <span class="fu">dec</span>(response_choice) <span class="sc">~</span> stimulus_type <span class="sc">*</span> Condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Participant) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Item),</span>
<span id="cb4-4"><a href=""></a>  </span>
<span id="cb4-5"><a href=""></a>  <span class="co"># 2. Boundary Separation (a): modulated by speed-accuracy instructions</span></span>
<span id="cb4-6"><a href=""></a>  boundary <span class="sc">~</span> Condition,</span>
<span id="cb4-7"><a href=""></a>  </span>
<span id="cb4-8"><a href=""></a>  <span class="co"># 3. Non-Decision Time (t0): sensory-motor latency across conditions</span></span>
<span id="cb4-9"><a href=""></a>  ndt <span class="sc">~</span> Condition,</span>
<span id="cb4-10"><a href=""></a>  </span>
<span id="cb4-11"><a href=""></a>  <span class="co"># 4. Starting Point Bias (z): bias toward "Word" (1) vs "Nonword" (0)</span></span>
<span id="cb4-12"><a href=""></a>  bias <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb4-13"><a href=""></a>  </span>
<span id="cb4-14"><a href=""></a>  <span class="co"># Baseline 4-parameter DDM (trial-to-trial variabilities fixed to 0)</span></span>
<span id="cb4-15"><a href=""></a>  <span class="at">sigmadrift =</span> <span class="dv">0</span>, <span class="at">sigmabias =</span> <span class="dv">0</span>, <span class="at">sigmandt =</span> <span class="dv">0</span>,</span>
<span id="cb4-16"><a href=""></a>  <span class="at">family =</span> <span class="fu">cogmod_ddm</span>()</span>
<span id="cb4-17"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="high-performance-multi-threading-in-stan" class="slide level2">
<h2>High-Performance Multi-Threading in Stan</h2>
<ul>
<li class="fragment">Fitting <span class="math inline">\(&gt;3,000\)</span> item intercepts across <span class="math inline">\(4,632\)</span> observations takes significant compute time.</li>
<li class="fragment"><strong>Solution:</strong> Within-chain multi-threading in Stan via <code>reduce_sum</code>:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>model_ddm <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb5-2"><a href=""></a>  <span class="at">formula  =</span> f_ddm,</span>
<span id="cb5-3"><a href=""></a>  <span class="at">data     =</span> df,</span>
<span id="cb5-4"><a href=""></a>  <span class="at">prior    =</span> prior_ddm,</span>
<span id="cb5-5"><a href=""></a>  <span class="at">init     =</span> init_ddm,</span>
<span id="cb5-6"><a href=""></a>  <span class="at">stanvars =</span> sv_ddm,</span>
<span id="cb5-7"><a href=""></a>  <span class="at">chains   =</span> <span class="dv">4</span>,</span>
<span id="cb5-8"><a href=""></a>  <span class="at">cores    =</span> <span class="dv">4</span>,</span>
<span id="cb5-9"><a href=""></a>  <span class="at">threads  =</span> <span class="fu">threading</span>(<span class="dv">2</span>), <span class="co"># 2 threads per chain = 8 cores active!</span></span>
<span id="cb5-10"><a href=""></a>  <span class="at">iter     =</span> <span class="dv">1000</span>,</span>
<span id="cb5-11"><a href=""></a>  <span class="at">warmup   =</span> <span class="dv">500</span>,</span>
<span id="cb5-12"><a href=""></a>  <span class="at">backend  =</span> <span class="st">"cmdstanr"</span>,</span>
<span id="cb5-13"><a href=""></a>  <span class="at">control  =</span> <span class="fu">list</span>(<span class="at">adapt_delta =</span> <span class="fl">0.95</span>, <span class="at">max_treedepth =</span> <span class="dv">12</span>)</span>
<span id="cb5-14"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div style="background: #E8F4F8; border-left: 5px solid #1F497D; padding: 12px; border-radius: 4px; font-size: 0.9em; margin-top: 15px;">
<p>🚀 <strong>How it works:</strong> Stan parallelizes likelihood evaluations across 2 threads <em>within each chain</em>. With 4 chains running simultaneously on 4 cores, all 8 CPU cores are pinned at 100%, cutting wall-clock execution time in half!</p>
</div>
</section>
<section id="mcmc-diagnostics-preventing-divergences" class="slide level2">
<h2>MCMC Diagnostics: Preventing Divergences</h2>
<ul>
<li class="fragment"><strong>What is a divergent transition?</strong>
<ul>
<li class="fragment">A point where the simulated Hamiltonian trajectory deviates from the true energy surface.</li>
<li class="fragment">Indicates that the step size <span class="math inline">\(\epsilon\)</span> is too large to navigate high-curvature regions.</li>
</ul></li>
<li class="fragment"><strong>Neal’s Funnel in Hierarchical DDMs:</strong>
<ul>
<li class="fragment">Estimating participant-level standard deviations (<span class="math inline">\(\sigma_{\text{Participant}}\)</span>) with only <span class="math inline">\(N=3\)</span> participants creates a classic “funnel” geometry.</li>
<li class="fragment">In our initial tests with default <code>adapt_delta = 0.80</code>, 36 divergences clustered in the funnel neck of <code>sd_Participant__Intercept</code>.</li>
</ul></li>
<li class="fragment"><strong>The Solution in <code>fit_ddm_stimulus_coding.R</code>:</strong>
<ul>
<li class="fragment"><code>adapt_delta = 0.95</code>: Forces Stan to take smaller leapfrog steps, resolving the narrow neck.</li>
<li class="fragment"><code>max_treedepth = 12</code>: Prevents premature termination of trajectory exploration in complex surfaces.</li>
</ul></li>
</ul>
</section>
<section id="model-results-full-hierarchical-ddm-n-17" class="slide level2 dark-bg" data-background-color="#1F497D">
<h2>Model Results: Full Hierarchical DDM (N = 17)</h2>
<div style="background: #E8F5E9; border-left: 5px solid #2E7D32; padding: 15px; border-radius: 6px; font-size: 0.9em; margin-bottom: 20px;">
<p>✅ <strong>Production Model Completed:</strong> The full hierarchical stimulus-coded DDM finished sampling in <strong>157.2 minutes</strong> (~2.6 hours) across 4 chains (1,000 iter, 500 warmup = 2,000 post-warmup draws) with multi-threading (<code>threads = threading(2)</code>).</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="mcmc-diagnostic-health">MCMC Diagnostic Health</h3>
<ul>
<li class="fragment"><strong>Divergent Transitions: 0 (0.0%)</strong> across all 2,000 draws!
<ul>
<li class="fragment"><code>adapt_delta = 0.95</code> eliminated divergences.</li>
</ul></li>
<li class="fragment"><strong>Rhat = 1.00</strong> across every parameter.</li>
<li class="fragment"><strong>Bulk ESS:</strong> 1,798 to 4,765 (far above the 400 guideline).</li>
<li class="fragment"><strong>Tail ESS:</strong> 1,127 to 1,898.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="modeling-scope">Modeling Scope</h3>
<ul>
<li class="fragment"><strong>31,351 observations</strong> (all 17 subjects, censored).</li>
<li class="fragment"><strong>4,780 crossed item intercepts</strong> estimated simultaneously.</li>
<li class="fragment"><strong>17 participant intercepts</strong> estimated simultaneously.</li>
<li class="fragment">Model serialized safely to: <code>models/ddm_cogmod_stimulus_coding_model.qs</code></li>
</ul>
</div></div>
</section>
<section id="posterior-parameter-estimates-full-production-model" class="slide level2">
<h2>Posterior Parameter Estimates (Full Production Model)</h2>
<div style="font-size: 0.58em;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">EstError</th>
<th style="text-align: center;">95% CrI</th>
<th style="text-align: center;">Rhat</th>
<th style="text-align: right;">Bulk_ESS</th>
<th style="text-align: left;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept (Grand Mean Drift)</td>
<td style="text-align: right;">0.793</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: center;">[0.73, 0.85]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">1798</td>
<td style="text-align: left;">Unweighted mean drift (positive due to 2:1 category imbalance)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boundary Separation (Intercept)</td>
<td style="text-align: right;">1.112</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: center;">[1.10, 1.13]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">3382</td>
<td style="text-align: left;">Baseline boundary: softplus(1.11) ≈ 1.40 evidence units</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Starting Point Bias (Intercept)</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: center;">[0.01, 0.04]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">3569</td>
<td style="text-align: left;">Starting bias: plogis(0.025) ≈ 0.506 (nearly unbiased)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-Decision Time (Intercept)</td>
<td style="text-align: right;">-1.102</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: center;">[-1.11, -1.10]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">3270</td>
<td style="text-align: left;">Baseline NDT: exp(-1.10) ≈ 332 ms latency</td>
</tr>
<tr class="odd">
<td style="text-align: left;">stimulus_type: Nonword vs Word</td>
<td style="text-align: right;">-1.439</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: center;">[-1.46, -1.42]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">2565</td>
<td style="text-align: left;">Lexical discrimination: Nonwords drift down (-), Words up (+)</td>
</tr>
<tr class="even">
<td style="text-align: left;">stimulus_type: Low vs High Word</td>
<td style="text-align: right;">-0.678</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: center;">[-0.73, -0.63]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">2779</td>
<td style="text-align: left;">Frequency effect: Low-frequency slower uptake than high</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Condition: Acc vs Speed</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: center;">[0.06, 0.12]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">2799</td>
<td style="text-align: left;">Slight overall drift modulation across instructions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nonword_vs_Word : Acc_vs_Speed</td>
<td style="text-align: right;">-0.043</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: center;">[-0.06, -0.02]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">2858</td>
<td style="text-align: left;">Modulation of lexical discrimination by speed/acc</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Low_vs_High : Acc_vs_Speed</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: center;">[0.02, 0.10]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">3586</td>
<td style="text-align: left;">Modulation of frequency sensitivity by speed/acc</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boundary Separation: Acc vs Speed</td>
<td style="text-align: right;">0.426</td>
<td style="text-align: right;">0.008</td>
<td style="text-align: center;">[0.41, 0.44]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">4765</td>
<td style="text-align: left;">Accuracy widens boundaries: a_Acc (1.73) &gt; a_Spd (1.09)!</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-Decision Time: Acc vs Speed</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: center;">[0.02, 0.03]</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: right;">2972</td>
<td style="text-align: left;">NDT difference between conditions is tiny (~17 ms)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="posterior-boundary-separation-accuracy-vs.-speed" class="slide level2">
<h2>Posterior Boundary Separation: Accuracy vs.&nbsp;Speed</h2>
<div class="columns">
<div class="column" style="width:45%;">
<h3 id="robust-shift-in-decision-caution">Robust Shift in Decision Caution</h3>
<ul>
<li class="fragment"><strong>Accuracy Instructions:</strong>
<ul>
<li class="fragment"><span class="math inline">\(\text{softplus}(1.112 + 0.426) \approx \mathbf{1.73}\)</span> evidence units.</li>
</ul></li>
<li class="fragment"><strong>Speed Instructions:</strong>
<ul>
<li class="fragment"><span class="math inline">\(\text{softplus}(1.112 - 0.426) \approx \mathbf{1.09}\)</span> evidence units.</li>
</ul></li>
<li class="fragment"><strong>Cognitive Finding:</strong>
<ul>
<li class="fragment">Boundaries are <strong><span class="math inline">\(58\%\)</span> wider</strong> under accuracy instructions.</li>
<li class="fragment">Participants trade speed for accuracy by adjusting the threshold distance (<span class="math inline">\(a\)</span>).</li>
</ul></li>
</ul>
</div><div class="column" style="width:55%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/stimulus_boundary_posteriors.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="posterior-drift-rates-hypotheses-confirmation" class="slide level2">
<h2>Posterior Drift Rates &amp; Hypotheses Confirmation</h2>
<div class="columns">
<div class="column" style="width:45%;">
<h3 id="decomposition-of-evidence-accumulation">Decomposition of Evidence Accumulation</h3>
<ol type="1">
<li class="fragment"><strong>Drift Intercept (<span class="math inline">\(\beta_0 = +0.79\)</span>):</strong>
<ul>
<li class="fragment">Positive as mathematically derived (<span class="math inline">\(\frac{2}{3}\bar{\mu}_{\text{word}} + \frac{1}{3}\mu_{\text{nonword}}\)</span>).</li>
</ul></li>
<li class="fragment"><strong>Helmert C1 (<code>Nonword_vs_Word</code> = <span class="math inline">\(-1.44\)</span>):</strong>
<ul>
<li class="fragment">Massively negative: Nonwords accumulate evidence toward 0, words toward 1!</li>
</ul></li>
<li class="fragment"><strong>Helmert C2 (<code>Low_vs_High Word</code> = <span class="math inline">\(-0.68\)</span>):</strong>
<ul>
<li class="fragment">Low-frequency words have lower accumulation slopes than high-frequency words.</li>
</ul></li>
</ol>
</div><div class="column" style="width:55%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/stimulus_drift_posteriors.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="latency-crossed-random-effects" class="slide level2">
<h2>Latency &amp; Crossed Random Effects</h2>
<div class="columns">
<div class="column" style="width:45%;">
<h3 id="non-decision-latency-t_0">Non-Decision Latency (<span class="math inline">\(t_0\)</span>)</h3>
<ul>
<li class="fragment"><strong>Baseline NDT:</strong> <span class="math inline">\(332\)</span> ms (<span class="math inline">\(95\%\)</span> CrI: <span class="math inline">\([331, 334]\)</span> ms).</li>
<li class="fragment"><strong>Speed vs.&nbsp;Accuracy:</strong> Only a <span class="math inline">\(17\)</span> ms shift (<span class="math inline">\(341\)</span> ms in Accuracy vs.&nbsp;<span class="math inline">\(324\)</span> ms in Speed).</li>
<li class="fragment"><strong>Bias (<span class="math inline">\(z\)</span>):</strong> <span class="math inline">\(0.506\)</span> (<span class="math inline">\(50.6\%\)</span>, essentially unbiased).</li>
</ul>
<h3 id="crossed-variances">Crossed Variances</h3>
<ul>
<li class="fragment"><strong>Item SD (<span class="math inline">\(\sigma_{\text{Item}} = 0.69\)</span>):</strong> Substantial lexical diversity across words and nonwords.</li>
<li class="fragment"><strong>Participant SD (<span class="math inline">\(\sigma_{\text{Participant}} = 0.09\)</span>):</strong> Consistent performance across participants.</li>
</ul>
</div><div class="column" style="width:55%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/stimulus_random_effects.png" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div></div>
</section>
<section id="part-6-reproducibility-workflow-architecture" class="slide level2 dark-bg" data-background-color="#C2002F">
<h2>Part 6: Reproducibility &amp; Workflow Architecture</h2>
</section>
<section id="separation-of-concerns-in-quarto-docker" class="slide level2">
<h2>Separation of Concerns in Quarto &amp; Docker</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="anti-pattern-mcmc-in-quarto">❌ Anti-Pattern: MCMC in Quarto</h3>
<ul>
<li class="fragment">Running <code>brm()</code> calls directly inside <code>.qmd</code> code chunks.</li>
<li class="fragment">Every minor typo or slide reformat triggers hours of re-compilation.</li>
<li class="fragment">Rendering timeouts and container memory exhaustion.</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="best-practice-standalone-execution">✅ Best Practice: Standalone Execution</h3>
<ul>
<li class="fragment">Standalone R script (<code>fit_ddm_stimulus_coding.R</code>) executes in Docker.</li>
<li class="fragment">Models are serialized to disk using <code>qs2::qs_save()</code>.</li>
<li class="fragment">Presentation only loads pre-computed summaries via <code>qs2::qs_read()</code>.</li>
<li class="fragment">Slide compilation is instant (&lt; 5 seconds)!</li>
</ul>
</div></div>
<div style="background: #E8F5E9; border-left: 5px solid #2E7D32; padding: 12px; border-radius: 4px; font-size: 0.9em; margin-top: 20px;">
<p>🔒 <strong>Serialization Protocol:</strong> Always use <code>qs2</code> (fast, stable C++ serialization). Never use the deprecated <code>qs</code> package!</p>
</div>
</section>
<section id="managing-large-model-objects-in-git" class="slide level2">
<h2>Managing Large Model Objects in Git</h2>
<ul>
<li class="fragment">Fitted hierarchical Bayesian models in <code>brms</code> with thousands of random effect draws exceed <strong>50–300 MB</strong>.</li>
<li class="fragment">Committing raw <code>.qs</code> files exceeds GitHub’s 100 MB file limit and bloats repository history.</li>
<li class="fragment"><strong>The Project’s File Splitting Utility (<code>file_manager.py</code>):</strong>
<ul>
<li class="fragment"><p><strong>Splitting:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href=""></a><span class="ex">python3</span> file_manager.py split models/ddm_cogmod_stimulus_coding_model.qs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Creates a SHA-256 <code>.hash</code> file and split <code>.part00X</code> chunks (&lt; 90 MB) for safe Git commits.</p></li>
<li class="fragment"><p><strong>Rebuilding:</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href=""></a><span class="ex">python3</span> file_manager.py join <span class="at">--all</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Reassembles all split chunks into full <code>.qs</code> objects upon container startup!</p></li>
</ul></li>
</ul>
</section>
<section id="summary-technical-checklist-for-ddm-in-brms" class="slide level2">
<h2>Summary: Technical Checklist for DDM in brms</h2>
<div style="background: #F4F6F9; border-left: 5px solid #1F497D; padding: 15px; border-radius: 6px; font-size: 0.9em;">
<p><strong>1. Choice Coding:</strong> Use Response Coding (<span class="math inline">\(0 = \text{Nonword}, 1 = \text{Word}\)</span>) for balanced boundaries and meaningful drift signs.<br><br> <strong>2. Data Preparation:</strong> Filter extreme anticipations and lapses; ensure RT is strictly in <strong>seconds</strong>.<br><br> <strong>3. cogmod Ecosystem:</strong> Leverage <code>cogmod_ddm()</code> with <code>softplus</code> boundaries, <code>cogmod_priors()</code>, <code>cogmod_inits()</code>, and <code>cogmod_stanvars()</code>.<br><br> <strong>4. Contrast Engineering:</strong> Apply orthogonal Helmert contrasts to factor levels and sum contrasts to conditions for interpretable intercepts.<br><br> <strong>5. Parallelization:</strong> Use <code>backend = “cmdstanr”</code> and <code>threads = threading(2)</code> to maximize multicore throughput.<br><br> <strong>6. Sampler Tuning:</strong> Increase <code>adapt_delta = 0.95</code> and <code>max_treedepth = 12</code> to eliminate Neal’s Funnel divergences.</p>
</div>
</section>
<section id="references" class="slide level2 smaller scrollable">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-burkner2017brms" class="csl-entry" role="listitem">
Bürkner, P.-C. (2017). Brms: An r package for bayesian multilevel models using stan. <em>Journal of Statistical Software</em>, <em>80</em>(1), 1–28. <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>
</div>
<div id="ref-heathcote2012linear" class="csl-entry" role="listitem">
Heathcote, A., &amp; Love, B. C. (2012). Linear ballistic accumulation technology. <em>Frontiers in Psychology</em>, <em>3</em>, 292. <a href="https://doi.org/10.3389/fpsyg.2012.00292">https://doi.org/10.3389/fpsyg.2012.00292</a>
</div>
<div id="ref-makowski2025cogmod" class="csl-entry" role="listitem">
Makowski, D. (2025). <em>Cogmod: Cognitive modeling in <span>R</span> with stan and brms</em>. <a href="https://dominiquemakowski.github.io/cogmod/" class="uri">https://dominiquemakowski.github.io/cogmod/</a>.
</div>
<div id="ref-schad2020how" class="csl-entry" role="listitem">
Schad, D. J., Vasishth, S., Hohenstein, S., &amp; Kliegl, R. (2020). How to capitalize on a priori contrasts in linear (mixed) models: A tutorial. <em>Journal of Memory and Language</em>, <em>110</em>, 104038. <a href="https://doi.org/10.1016/j.jml.2019.104038">https://doi.org/10.1016/j.jml.2019.104038</a>
</div>
<div id="ref-singmann2017wiener" class="csl-entry" role="listitem">
Singmann, H. (2017). <em>Diffusion/<span>W</span>iener model analysis with brms – <span>P</span>art <span>I</span>: Introduction and estimation</em>. Computational Psychology blog. <a href="http://singmann.org/wiener-model-analysis-with-brms-part-i/" class="uri">http://singmann.org/wiener-model-analysis-with-brms-part-i/</a>.
</div>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="drift_diffusion_modeling_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>